"use client";
import { ArrowUpRight, ArrowRight, Sparkles, AudioLines, Terminal, Check, Layers } from "lucide-react";
import { motion } from "motion/react";
import type { Project } from "@/lib/schema";
import { Card, CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "./ui/accordion";
import { TrackedLink, useAnalytics } from "./analytics";
export function ProjectVisual({kind}:{kind:Project["visual"]}) {
  if(kind==="vidrush") return <div className="project-visual vidrush-visual" aria-hidden="true"><div className="visual-caption"><Sparkles size={12}/> FROM AN IDEA TO A VIDEO</div><div className="film-window"><div className="film-title"><span className="film-logo">v.</span><span>your next story</span><span className="ml-auto text-[9px]">01 / 03</span></div><div className="film-image"><div className="film-orbit"/><span>A little imagination.<br/>A new possibility.</span><div className="film-play">▶</div></div><div className="film-timeline"><AudioLines/><i/><i/><i/><i/><i/><i/><i/></div></div><span className="visual-footnote">PRODUCT WORKFLOW / ILLUSTRATION</span></div>;
  return <div className="project-visual opsmith-visual" aria-hidden="true"><div className="visual-caption"><Terminal size={12}/> FROM COMPLEXITY TO CLARITY</div><div className="terminal-window"><div className="terminal-top"><span/><span/><span/><p>opsmith / agent workspace</p></div><div className="terminal-body"><div className="terminal-prompt">How can we make on-call easier?</div><p><span>01</span> Understand the workflow</p><p><span>02</span> Validate the assumptions</p><p><span>03</span> Build, learn, iterate<span className="cursor-block"/></p><div className="terminal-status"><Check size={12}/> 34 conversations. A clearer direction.</div></div></div><span className="visual-footnote">DISCOVERY → DELIVERY / ILLUSTRATION</span></div>;
}
export function CaseDetails({project}:{project:Project}) {
  const track=useAnalytics();
  return <Accordion type="single" collapsible onValueChange={value=>{if(value) track("case_detail_open",{project:project.slug,detail:value});}}>{project.details.map((detail,i)=><AccordionItem value={detail.title} key={detail.title}><AccordionTrigger><span className="mr-2 font-mono text-[10px] text-muted-foreground">0{i+1}</span><span className="mr-auto">{detail.title}</span></AccordionTrigger><AccordionContent>{detail.text}</AccordionContent></AccordionItem>)}</Accordion>;
}
export function ProjectCard({project,index}:{project:Project;index:number}) {
  return <motion.article initial={false} whileHover={{y:-3}} transition={{duration:0.2}} className="min-w-0"><Card className="featured-card h-full overflow-hidden"><TrackedLink href={`/work/${project.slug}`} item={project.slug} event="project_open" aria-label={`Read ${project.title} case study`} className="block"><ProjectVisual kind={project.visual}/></TrackedLink><CardContent className="p-6 sm:p-7"><div className="mb-4 flex items-center justify-between gap-2"><span className="eyebrow">0{index+1} / {project.period}</span><Badge>#{project.category}</Badge></div><TrackedLink href={`/work/${project.slug}`} item={project.slug} event="project_open" className="project-heading"><h3>{project.title}</h3><ArrowUpRight className="size-5"/></TrackedLink><p className="mt-2 max-w-sm text-[15px] leading-relaxed text-muted-foreground">{project.subtitle}</p><div className="metric-row">{project.metrics.map(metric=><div key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span></div>)}</div><CaseDetails project={project}/><div className="mt-5 flex flex-wrap items-center justify-between gap-x-4 gap-y-2"><TrackedLink href={`/work/${project.slug}`} item={project.slug} event="project_open" className="text-link">Read the story <ArrowRight size={14}/></TrackedLink><TrackedLink href={project.links[0].href} item={project.slug} className="text-link text-muted-foreground">{project.links[0].label}<ArrowUpRight size={14}/></TrackedLink></div></CardContent></Card></motion.article>;
}
export function SmallProject({project}:{project:Project}) {
 return <article className="small-project"><span className={`small-project-icon ${project.visual}`} aria-hidden>{project.visual==="terminal"?<Terminal/>:project.visual==="growth"?<Sparkles/>:<Layers/>}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><TrackedLink href={`/work/${project.slug}`} event="project_open" item={project.slug} className="small-project-title">{project.title}<ArrowUpRight size={15}/></TrackedLink><Badge variant="outline">#{project.category}</Badge></div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{project.summary}</p><div className="mt-3 flex flex-wrap gap-4">{project.links.map(link=><TrackedLink key={link.href} href={link.href} item={`${project.slug}:${link.label}`} className="text-link text-xs">{link.label}<ArrowUpRight size={12}/></TrackedLink>)}</div></div></article>;
}
