"use client";
import { useRef,useState } from "react";
import { ArrowLeft,ArrowRight,ArrowUpRight,Quote } from "lucide-react";
import type { z } from "zod";
import type { testimonialSchema } from "@/lib/schema";
import { useAnalytics, TrackedLink } from "./analytics";
type Recommendation=z.infer<typeof testimonialSchema>;
export function TestimonialSection({items}:{items:Recommendation[]}) {
  const [index,setIndex]=useState(0);const track=useAnalytics();const startX=useRef<number|null>(null);
  const change=(next:number)=>{setIndex((next+items.length)%items.length);track("recommendation_change",{index:(next+items.length)%items.length});};
  const item=items[index];
  return <section className="section recommendations" aria-labelledby="recommendations-title"><div className="section-heading"><div><span className="eyebrow">03 / BETTER TOGETHER</span><h2 id="recommendations-title">Good work is a team sport.</h2></div><div className="flex gap-2"><button type="button" className="icon-button bordered" aria-label="Previous recommendation" onClick={()=>change(index-1)}><ArrowLeft size={17}/></button><button type="button" className="icon-button bordered" aria-label="Next recommendation" onClick={()=>change(index+1)}><ArrowRight size={17}/></button></div></div><div className="quote-layout" aria-roledescription="carousel" aria-label="LinkedIn recommendations" onTouchStart={e=>{startX.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(startX.current!==null){const dx=e.changedTouches[0].clientX-startX.current;if(Math.abs(dx)>60)change(index+(dx<0?1:-1));startX.current=null;}}}><div className="quote-aside"><Quote className="size-10 text-primary" strokeWidth={1}/><p>A few words from<br/>the people I’ve built with.</p><TrackedLink href="https://www.linkedin.com/in/nayana-k-955411170/" item="linkedin-recommendations" className="text-link text-xs">View LinkedIn<ArrowUpRight size={12}/></TrackedLink></div><figure className="quote-main" aria-live="polite" aria-atomic="true"><blockquote>{item.quote}</blockquote>{item.excerpt&&<p className="mt-3 text-xs text-muted-foreground">Excerpt from a longer recommendation.</p>}<figcaption><span className="initial-avatar" aria-hidden>{item.name.split(" ").filter(s=>!s.startsWith("(")).map(s=>s[0]).slice(0,2).join("")}</span><div><strong>{item.name}</strong><p>{item.headline}</p><small>{item.date} · {item.relationship}</small></div></figcaption></figure></div><div className="recommendation-progress"><span className="eyebrow" aria-live="polite">0{index+1} / 0{items.length}</span><div className="flex gap-1">{items.map((item,i)=><button key={item.name} type="button" className="progress-button" aria-label={`Show recommendation from ${item.name}`} aria-pressed={i===index} onClick={()=>change(i)}><span/></button>)}</div><span className="text-[10px] text-muted-foreground">Headlines as shown on LinkedIn, Sep 2026</span></div></section>;
}
